CREATE DATABASE IF NOT EXISTS habitflow;
CREATE USER IF NOT EXISTS 'VINOTH'@'localhost' IDENTIFIED BY 'vinothkumar123';
ALTER USER 'VINOTH'@'localhost' IDENTIFIED BY 'vinothkumar123';
CREATE USER IF NOT EXISTS 'VINOTH'@'%' IDENTIFIED BY 'vinothkumar123';
ALTER USER 'VINOTH'@'%' IDENTIFIED BY 'vinothkumar123';
GRANT ALL PRIVILEGES ON habitflow.* TO 'VINOTH'@'localhost';
GRANT ALL PRIVILEGES ON habitflow.* TO 'VINOTH'@'%';
FLUSH PRIVILEGES;
