CREATE DATABASE IF NOT EXISTS habitflow;

CREATE USER IF NOT EXISTS 'VINOTH'@'localhost' IDENTIFIED BY 'vinothkumar123';
ALTER USER 'VINOTH'@'localhost' IDENTIFIED BY 'vinothkumar123';
CREATE USER IF NOT EXISTS 'VINOTH'@'%' IDENTIFIED BY 'vinothkumar123';
ALTER USER 'VINOTH'@'%' IDENTIFIED BY 'vinothkumar123';

GRANT ALL PRIVILEGES ON habitflow.* TO 'VINOTH'@'localhost';
GRANT ALL PRIVILEGES ON habitflow.* TO 'VINOTH'@'%';
FLUSH PRIVILEGES;

USE habitflow;

CREATE TABLE IF NOT EXISTS users (
  id VARCHAR(64) PRIMARY KEY,
  full_name VARCHAR(120) NOT NULL,
  identifier VARCHAR(160) NOT NULL UNIQUE,
  password_hash VARCHAR(255) NOT NULL,
  password_salt VARCHAR(255) NOT NULL,
  created_at DATE NOT NULL
);

CREATE TABLE IF NOT EXISTS user_data (
  user_id VARCHAR(64) PRIMARY KEY,
  habits_json LONGTEXT NOT NULL,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  CONSTRAINT fk_user_data_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);
